---
ssh_permit_root_login: "no" # sshd_disable_root_login
ssh_permit_empty_passwords: "no" # sshd_disable_empty_passwords
ssh_password_authentication: "no" # sshd_disable_password_auth (we use key auth)
ssh_max_auth_tries: 4 # sshd_set_max_auth_tries
ssh_client_alive_interval: 300 # sshd_set_idle_timeout
ssh_client_alive_count_max: 3 # sshd_set_keepalive
ssh_login_grace_time: 60 # sshd_set_login_grace_time
ssh_max_sessions: 10 # sshd_set_max_sessions
ssh_x11_forwarding: "no" # sshd_disable_x11_forwarding
ssh_log_level: "VERBOSE" # sshd_set_loglevel_verbose
ssh_ignore_rhosts: "yes" # sshd_disable_rhosts
ssh_hostbased_authentication: "no" # disable_host_auth
ssh_permit_user_environment: "no" # sshd_do_not_permit_user_env
ssh_banner: /etc/issue.net # sshd_enable_warning_banner
